### ISSUE TITLE
Strange behaviour with absolute path

### ISSUE THREAD

**Issue by ccarouge** [coecms/mdssdiff#11]
This command works as expected:
`mdssdiff -r -p mxs561/CABLE_offline /g/data/w35/mxs561/CABLE_offline`

But this:
`mdssdiff -r -cr -p mxs561/CABLE_offline /g/data/w35/mxs561/CABLE_offline`

tries to create the path `/g/data/w35/mxs561/CABLE_offline` on mdss which obviously can't be done as it is an absolute path.
I am not totally sure what behaviour we'd like in this case.

**Comment by ccarouge** [comment]
Should mdssdiff look for the prefix in the path provided? 
If found, then take whatever is after and create the directory tree needed. 
If found and the path ends there (as above), then no need to create anything, the prefix path is the destination path.
If not found in the absolute path, then take the last directory name from the absolute path and create a folder with that name in the prefix path under mdss?

**Comment by aidanheerdegen** [comment]
I think check for an absolute path and issue an error in that case. All paths have to be relative for `mdssdiff` to work

**Comment by ccarouge** [comment]
Except I don't necessarily want mdss to create the path I give. For example, I'm now testing with this:
`mdssdiff -r -cr -p mxs561/CABLE_offline ../mxs561/CABLE_offline`
What will happen with the `../` ? And that means you can't have your script in one filesystem (e.g. home) and archive stuff under `/g/data` unless you created some symlinks before.

**Comment by aidanheerdegen** [comment]
The intention in the case above would be to do like so:
```
cd ../mxs561/
mdssdiff -r -cr -p mxs561 CABLE_offline
```
it really is just intended to compare a directory hierarchy on a local disk to the same directory hierarchy  with a different prefix on `mdss`.
